main:
  - name: "Home"
    url: "#about"
    weight: 10
  
  - name: "Projects"
    url: "#projects"
    weight: 30

  # - name: "Posts"
  #   url: "#posts"
  #   weight: 20
  
  - name: "Publications"
    url: "#publications"
    weight: 40
  - name: "Talks"
    url: "#talks"
    weight: 50

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
  # - name: "CV"
  #   url: "files/cv.pdf"
  #   weight: 70